### ISSUE TITLE
タイトル画面

### ISSUE THREAD

**Issue by acro-yanagida** [acro-takahashi/SapporoFPS#18]
## 欲しい機能はなに?
ゲーム始める前にSapporoFPSのタイトル画面がほしい
## なぜその機能が欲しい?
ゲーム始める前にワンクッション置きたい

**Comment by acro-takahashi** [comment]
起動＞unityロゴ＞ゲーム画面
から
起動＞unityロゴ＞タイトル画面＞ゲーム画面の画面遷移順にする

♯ 参考URL
https://freesworder.net/unity-scene-change/

**Comment by acro-nakanishi** [comment]
Command + Shift + Nで空のオブジェクトを作る
新規スクリプトを作成する

スクリプトを編集し、using UnityEngine.SceneManagement;を追加
void Update()の中に、
if (Input.GetMouseButtonDown (0)) {
SceneManager.LoadScene ("MainScene");
}
を追加する

最後にファイルからビルド設定に進んで、
Scenes In BuildにMainSceneとTitleSceneをドラッグアンドドロップ

以上で左クリックするとMainSceneへ進めるようになる
