### ISSUE TITLE
ジャンプ改善

### ISSUE THREAD

**Issue by acro-takahashi** [acro-takahashi/SapporoFPS#2]
## 自由に記載
ジャンプ動作が明らかにオーバーモーションに対してジャンプ量が小さい

モーション時間の関係もあるだろうから
とりあえず
・ジャンプの高さ調整
・ジャンプ中に走るモーションを行わない
のどちらか片方だけでも出来るようにする

## 参考URL
https://xr-hub.com/archives/8808

**Comment by acro-yanagida** [comment]
〇改善準備
　下記URLのアセットを入れる
[https://assetstore.unity.com/packages/tools/game-toolkits/third-person-controller-basic-locomotion-free-82048](url)
〇改善方法
　invector >BasicLocomotion >CreateBasicControllreを開く
<img width="314" alt="jump1" src="https://user-images.githubusercontent.com/91652652/137436576-75fafafc-50e0-4804-a506-68828a9d02f6.png">
　FBXはunityちゃんなど動かしたいアセットを選択
　AnimatorはInvectorを選択してcreateをクリックすると
　ジャンプを改善したキャラを扱える
<img width="502" alt="jump2" src="https://user-images.githubusercontent.com/91652652/137437044-b08f0f11-e00f-44ce-9597-eb6240e0b178.png">

〇メモ
・prefabsからキャラを生成してスクリプトをおじさんに代入したときに起きた問題
　左右の動作が棒立ちのまま移動、キューブの淵にジャンプしたときの動作が以前のまま
・今回方法による問題
　しゃがむことができない（方法がわからない）
