### ISSUE TITLE
【エラーハンドル】特定座標に移動キーの実装　#20類似

### ISSUE THREAD

**Issue by acro-takahashi** [acro-takahashi/SapporoFPS#22]
## 欲しい機能はなに?
埋まりなどで操作不能になった場合にスタート地点にワープするキーを実装したい

## なぜその機能が欲しい?
はまり発生時に進行不能になるから

## 実装方法
未使用のキー押下時に座標を指定してオブジェクトを移動させる
※#20 が実装された後ならY軸落下だけでもいいかも

## 参考URL
https://mono-pro.net/archives/7582

**Comment by koshirokanda** [comment]
# ワープを実装しよう
*完成図*
![オブジェクトワープ](https://user-images.githubusercontent.com/96943712/169060400-df18e148-9fd8-45a7-9497-576998b093f4.gif)


###  1. ヒエラルキーカテゴリの赤枠の部分を右クリックして、メニューを出す
<img src="https://user-images.githubusercontent.com/96943712/169016471-e5932780-25c0-4032-8e44-e899a0dc59cd.png" width="75%">


### 2. メニュー「3Dオブジェクト」にマウスカーソルを合わせ、その中の「平面」をクリックする
<img src="https://user-images.githubusercontent.com/96943712/169016053-752228f2-ea93-4ea1-8ad5-79da44dc667d.png" width="75%">

↓選択後は下記のような平面ができます
<img src="https://user-images.githubusercontent.com/96943712/169016840-a9f3f56e-c78d-4935-816f-246ef5a040a5.png" width="75%">

### 3. ヒエラルキーカテゴリの赤枠の部分を右クリックして、メニューを出す
<img src="https://user-images.githubusercontent.com/96943712/169017455-291bde17-7c2f-4258-a725-ac73685690aa.png" width="75%">


### 4. メニュー「3Dオブジェクト」にマウスカーソルを合わせ、さらにメニュー中の「シリンダー」を選択する
<img src="https://user-images.githubusercontent.com/96943712/169018081-d339a534-b39d-4fac-a413-d83f6553a4d1.png" width="75%">

↓選択後は下記のような円柱のオブジェクトができます
<img src="https://user-images.githubusercontent.com/96943712/169018300-4713ba87-a4b0-4315-aa49-b830f43e1a80.png" width="75%">



### 5. シリンダーを右クリックして、メニューから名前の変更を選択⇒「PlayerWarp」に変更
<img src="https://user-images.githubusercontent.com/96943712/169018525-1bd6fb77-4fbf-4593-ae68-57687864e172.png" width="75%">

↓変更後は下記のようになります
<img src="https://user-images.githubusercontent.com/96943712/169024047-9c83b1d7-1c82-4d5a-9130-020939b83ca6.png" width="75%">


### 6. シリンダー「PlayerWarp」を選択＞インスペクター＞コンポーネントの追加＞新しいスクリプトを「PlayerWarp」で作成
<img src="https://user-images.githubusercontent.com/96943712/169029047-03724ab1-94de-4f74-9647-85f3c282b7c8.png" width="75%">


### 7. スクリプト「PlayerWarp」のスクリプトを編集を選択する
<img src="https://user-images.githubusercontent.com/96943712/169029748-9a350c6d-593e-46cf-a8f9-c07632fc51e5.png" width="75%">


### 8. スクリプトが開いたら、下記のコードを入力(保存する）
<img src="https://user-images.githubusercontent.com/96943712/169030610-830de7f3-b24d-4c84-ae2b-05c83e279873.png" width="75%">

``` 
public class PlayerWarp : MonoBehaviour
{
    [Header("ワープする座標（Rキー）")]
    public float X = 0f;
    public float Y = 0f;
    public float Z = 0f;

    // Start is called before the first frame update


    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.R))
        {
                transform.position = new Vector3(X, Y, Z);
        }

    }
    void OnCollisionEnter(Collision obj)
    {
        if (obj.transform.name == "WarpObject")
        //　「""」の中はどのオブジェクトと衝突するか
        {
                transform.position = new Vector3(X, Y, Z);
        }
    }
}
```
↓判定のあるオブジェクトを指定する（指定しないと反応がない）
<img src="https://user-images.githubusercontent.com/96943712/169041957-126d0477-acd6-413a-a69e-2641d959bd6a.png" width="75%">

↓保存してUnityに戻るとセクターが表示される
<img src="https://user-images.githubusercontent.com/96943712/169031948-10f93d46-b85d-485b-9907-454aacdf3d04.png" width="75%">

### 9. Prefabes ＞キャラセットから「TestUnityChan」をヒエラルキーにドラッグする
<img src="https://user-images.githubusercontent.com/96943712/169032515-dc86273c-7158-490f-853c-77e8629fff92.png" width="75%">

↓「TestUnityChan」ドロップすると下記のように表示される
<img src="https://user-images.githubusercontent.com/96943712/169032723-74d513a8-5ee8-40f0-bc04-8af8d46ae028.png" width="75%">

### 9. 「TestUnityChan」の配置を調整する
<img src="https://user-images.githubusercontent.com/96943712/169042407-63bb566a-3a67-429d-b318-41dcfe674009.png" width="75%">

### 10. 再生➤ボタンを押して、「TestUnityChan」を「WarpPoint」に接触させて実装確認する
<img src="https://user-images.githubusercontent.com/96943712/169056564-04a0d133-a7f3-4b5f-a84e-cf5d434f629c.png" width="75%">
