### ISSUE TITLE
爆弾

### ISSUE THREAD

**Issue by acro-yanagida** [acro-takahashi/SapporoFPS#8]
## 欲しい機能はなに?
広範囲に攻撃できる爆弾を使いたい

## なぜその機能が欲しい?
楽しそうだから

**Comment by acro-takahashi** [comment]
空のオブジェクトを生成→スフィアコライダーで見えない弾上のコリジョンを作る→それを当たり判定にしてダメージ判定で出来そう
https://your-3d.com/unity-particle-script-1/

**Comment by acro-yanagida** [comment]
1．爆弾のオブジェクトを作成する（スフィアなど）
2．爆弾オブジェクトにエフェクトをつけ、
　エフェクトに当たると衝撃が伝わるようにしたいため、
　スクリプトを作成する（名前はFireとする）
3．スクリプトに以下のコードを記入する
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Fire : MonoBehaviour
{
    public GameObject particleObject;

    private void OnCollisionEnter(Collision collision)
    {  
        if (collision.gameObject.tag == "Object") //Objectタグの付いたゲームオブジェクトと衝突したか判別
        {
            Instantiate(particleObject, this.transform.position, Quaternion.identity); //パーティクル用ゲームオブジェクト生成
            Destroy(this.gameObject); //衝突したゲームオブジェクトを削除
        }
    }
}　
4．使用するエフェクトはヒエラルキーに出し、
　ループをすべてチェック外し、インスペクターの衝突にチェックを入れ、
　タイプをワールド、衝突メッセージを送信にチェックを入れる
<img width="331" alt="エフェクト" src="https://user-images.githubusercontent.com/91652652/140301926-5e1aa09c-f82c-411e-90e8-a0348fbf2ce1.png">
5．爆弾のオブジェクトにFireスクリプトを入れ、
　Fireスクリプトのプレハブオブジェクトに上記のエフェクトを入れる
6．球を前に投げられるようにするスクリプトを作成する（名前はBombShotとする）
public class BombShot : MonoBehaviour
{
public GameObject grenadePrefab;
    public AudioClip throwSound;
    public float throwSpeed;
    public int grenadeCount;//爆弾の数を入力できる
    public Text bombText;
   

	void Update () {
        if(Input.GetKeyDown(KeyCode.Mouse1) && grenadeCount > 0){　//マウス右クリックで爆弾発射
            grenadeCount -= 1;

            GameObject grenade = (GameObject)Instantiate(grenadePrefab, transform.position, Quaternion.identity);
            Rigidbody grenadeRb = grenade.GetComponent<Rigidbody>();
            grenadeRb.AddForce(transform.forward * throwSpeed);
            AudioSource.PlayClipAtPoint(throwSound, Camera.main.transform.position);
            }
       }
}
7．6で作成したスクリプトをaonCamerasonCamera（shotとか実装してるカメラ）に入れる
　赤線部分に爆弾オブジェクトを入れ、青線部分は爆弾の個数を入力できる
<img width="336" alt="bomb" src="https://user-images.githubusercontent.com/91652652/140297521-de16d359-70c8-4259-aa90-f93a42f862b4.png">
8．爆弾の残数表示は#18HPを視覚的に表示させるためにのhitPointをbombに変更して、
　BombShot スクリプトに追加する
9．爆発の衝撃を伝えたいものにはタグをEnemyに指定する
<img width="327" alt="タグ" src="https://user-images.githubusercontent.com/91652652/140303711-30478928-fda0-4fc4-b034-23213ea8a350.png">
